name: Deploy Next.js Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            set -e # 오류 발생 시 즉시 종료

            # 애플리케이션 디렉토리로 이동
            cd ${{ secrets.APP_DIR }}

            # 최신 코드 가져오기
            git fetch origin main
            git reset --hard origin/main

            # 환경 변수 설정
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            # pnpm 설치 확인 및 설치 (필요한 경우)
            if ! command -v pnpm &> /dev/null; then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              source ~/.bashrc
            fi

            # 의존성 설치
            pnpm install

            # 프로젝트 빌드
            pnpm build

            # PM2로 애플리케이션 재시작
            pm2 restart next-app --update-env || pm2 start "pnpm start" --name "next-app"

            # PM2 설정 저장
            pm2 save
